name: Pull request on master action

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run tests
      run: sbt test

    - name: Docker publish
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.DOCKER_REPOSITORY }}
        sbt -Ddocker.tags.branch=${{ steps.extract_branch.outputs.branch }} -Ddocker.organization=arajoa -Ddocker.repository=${{ secrets.DOCKER_REPOSITORY }} docker:publish